# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request: 
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch: 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"  
  build:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    uses: sparqlunicorn/sparqlunicornGoesGIS-ontdoc/.github/workflows/udoc.yml@main
    with: 
        version: v016
        rdffilepath: spp_result.ttl
        docpath: docs
        prefixns: http://data.archaeology.link/data/spphaefen/
        prefixnsshort: spp
        indexpages: true
        createcollections: true
        createnonNSPages: true
        createVOWL: true
        metadatatable: true
        preferredlang: en
        license: CC BY-NC-SA 4.0
        startconcept: http://data.archaeology.link/data/spphaefen/Harbour_collection
        ghpages: true
